routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PelajarController;
use App\Http\Controllers\ProgramController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    echo 'hello world';
    // return view('welcome');
});


Route::get('test1', function () {
     echo 'ini test';
});

// Route::get('pelajar', [PelajarController::class, 'index'])->name('pelajar.index');



Route::middleware(['auth'])->group(function () {

Route::middleware(['rbac:R001,R002'])->group(function () {
    Route::resource('pelajar', PelajarController::class);
});
   
});





Route::resource('program', ProgramController::class);



Auth::routes();

// Auth::routes(['register'=>false]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/PelajarController.php
<?php

namespace App\Http\Controllers;

use App\Models\Student;
use App\Models\LevelStudent;
use Illuminate\Http\Request;
use App\Helpers\CustomHelper;
use App\Models\StudentsModel;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\App;

class PelajarController extends Controller
{
    public function index(Request $request){


       $lookupCitizen= CustomHelper::lookupCitizen();
       $lookupGender= CustomHelper::lookupGeneral('gender');


        $Student=Student::with(['lookupCitizen','lookupGender','levelStudent'])
        ->filter($request)
        ->paginate(20);

        // dd($Student);


        return view('pelajar.index',compact('Student','lookupCitizen','lookupGender'));

    }
    //


 /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $lookupCitizen= CustomHelper::lookupCitizen();
        $lookupGender= CustomHelper::lookupGeneral('gender');


        return view('pelajar.create',compact('lookupCitizen','lookupGender'));

        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        
        // kalu empty boleh guna nullable "matric_no" =>'nullable',
      $datavalidat=  $request->validate([
         "full_name" =>'required', 
         "identity" => 'required',
         "citizen_type" => 'required',
         "matric_no" => 'required|min:8',
        ],[
            'full_name.required'=>'Nama Penuh Wajib Di isi',
            'citizen_type.required'=>' Wajib Di isi',
         ]);

         $datavalidat['level_session']='1 2023/2024';
    
         DB::beginTransaction();

         try {

            $student= Student::create($datavalidat);

            if($student->id??''){
    
                $datavalidat['student_id']=$student->id;
                LevelStudent::create($datavalidat);
            }
            
            DB::commit();
    
            return redirect()->route('pelajar.index')
            ->withSuccess('Pelajar Created')->with(['name_student'=>$student->full_name]);
          

        } catch (\Throwable $th) {
            
            // dd($th);

            DB::rollback();
           return redirect()->back()->withErrors(['erros'])->withInput();

        }


   


        


        
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }

}

resources/views/pelajar/create.blade.php
@extends('layouts.app')
 
@section('title', 'Tambah Pelajar')
 
@section('content')

{{print_r($errors->all())}};

{{-- form --}}
<form class="form form-horizontal" method='POST' action="{{route('pelajar.store')}}" >
  @csrf
    <div class="form-body">
        <div class="row">
            <div class="col-md-4">
                <label for="first-name-horizontal">Full Name</label>
            </div>
            <div class="col-md-8 form-group">
                <input value='{{old('full_name')}}' type="text" id="first-name-horizontal"
                 class="form-control @error('full_name')?? is-invalid @enderror " name="full_name" placeholder="First Name">
               

                @error('full_name')
                    <span class="text-danger">{{$message}}</span>
                @enderror

            </div>
            <div class="col-md-4">
                <label for="identity-horizontal">Identity</label>
            </div>
            <div class="col-md-8 form-group">
                <input  value='{{old('identity')}}' type="text" id="identity-horizontal" class="form-control" name="identity" placeholder="identity">
            </div>
            <div class="col-md-4">
                <label for="contact-info-horizontal">Citizen</label>
            </div>
            <div class="col-md-8 form-group">
               
                <select name="citizen_type" id="contact-info-horizontal"
                 class="form-control @error('citizen_type')?? is-invalid @enderror">
                    <option value="">Sila pilih</option>
                    @php
                        $keycit=$rowcit=null;
                    @endphp
                    @foreach ($lookupCitizen as $keycit=>$rowcit)
                         <option {{ old('citizen_type') == $keycit? 'selected' : '' }} value="{{$keycit}}">{{$rowcit}}</option>
                    @endforeach
                </select>

                @error('citizen_type')
                <span class="text-danger">{{$message}}</span>
                @enderror

            </div>
            <div class="col-md-4">
                <label for="matric-horizontal">No Matric</label>
            </div>
            <div class="col-md-8 form-group">
                <input type="text" id="password-horizontal" class="form-control" name="matric_no" placeholder="Password">
            </div>
            <div class="col-12 col-md-8 offset-md-4 form-group">
                <div class="form-check">
                    <div class="checkbox">
                        <input type="checkbox" id="checkbox1" class="form-check-input" checked="">
                        <label for="checkbox1">Remember Me</label>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 d-flex justify-content-end">
                <button type="submit" class="btn btn-primary me-1 mb-1">Submit</button>
                <a class="btn btn-light-secondary me-1 mb-1" href="{{route('pelajar.index')}}">Reset</a>
                <button type="reset" class="btn btn-light-secondary me-1 mb-1">Reset</button>
            </div>
        </div>
    </div>
</form>

{{-- end form --}}

@endsection

resources/views/pelajar/index.blade.php
@extends('layouts.app')
 
@section('title', 'Pelajar')
 
@section('content')


@if (session('success'))
    <div class='alert alert-success'>
        {{session('success')}}
        {{session('name_student')}}

    </div>
@endif


{{-- form --}}
<form class="form form-horizontal" action="{{route('pelajar.index')}}" >
                                <div class="form-body">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <label for="first-name-horizontal">Full Name</label>
                                        </div>
                                        <div class="col-md-8 form-group">
                                            <input value='{{request('full_name')}}' type="text" id="first-name-horizontal" class="form-control" name="full_name" placeholder="First Name">
                                        </div>
                                        <div class="col-md-4">
                                            <label for="identity-horizontal">Identity</label>
                                        </div>
                                        <div class="col-md-8 form-group">
                                            <input type="text" id="identity-horizontal" class="form-control" name="identity" placeholder="identity">
                                        </div>
                                        <div class="col-md-4">
                                            <label for="contact-info-horizontal">Citizen</label>
                                        </div>
                                        <div class="col-md-8 form-group">
                                           
                                            <select name="citizen_type" id="contact-info-horizontal" class="form-control">
                                                <option value="">Sila pilih</option>
                                                @php
                                                    $keycit=$rowcit=null;
                                                @endphp
                                                @foreach ($lookupCitizen as $keycit=>$rowcit)
                                                     <option {{ request('citizen_type') == $keycit? 'selected' : '' }} value="{{$keycit}}">{{$rowcit}}</option>
                                                @endforeach
                                            </select>

                                        </div>
                                        <div class="col-md-4">
                                            <label for="matric-horizontal">No Matric</label>
                                        </div>
                                        <div class="col-md-8 form-group">
                                            <input type="password" id="password-horizontal" class="form-control" name="password" placeholder="Password">
                                        </div>
                                        <div class="col-12 col-md-8 offset-md-4 form-group">
                                            <div class="form-check">
                                                <div class="checkbox">
                                                    <input type="checkbox" id="checkbox1" class="form-check-input" checked="">
                                                    <label for="checkbox1">Remember Me</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-12 d-flex justify-content-end">
                                            <button type="submit" class="btn btn-primary me-1 mb-1">Submit</button>
                                            <a class="btn btn-light-secondary me-1 mb-1" href="{{route('pelajar.index')}}">Reset</a>
                                            <button type="reset" class="btn btn-light-secondary me-1 mb-1">Reset</button>
                                        </div>
                                    </div>
                                </div>
                            </form>

{{-- end form --}}

{{-- button add --}}

<a class='btn btn-info' href="{{route('pelajar.create')}}">Tambah</a>

{{-- button add end--}}


<table class='table'>


    <tr>
        <th>col1</th>
        <th>col1</th>
        <th>col1</th>
        <th>col1</th>
    </tr>

@foreach ($Student as $key=>$item)

    <tr>
       <td>{{$Student->firstItem()+$key}}</td>
        <td>{{$item->full_name??''}}</td>
        <td>{{$item->lookupCitizen->name??''}}</td>
        <td>{{$item->lookupGender->name??''}}</td>
        <td>{{$item->levelStudent->matric_no??''}}</td>
        <td>{{$item->levelStudent->level_semester??''}}</td>
    </tr>

 @endforeach

</table>

{{$Student->appends(request()->except('page'))->links()}}


    

@endsection

@section('scripts')

<script>
@if (session('success'))
Swal.fire({
  position: "top-end",
  icon: "success",
  title: "Your work has been saved",
  showConfirmButton: false,
  timer: 1500
});
@endif



</script>

@endsection